experiment:
    id: experiment_004
    seed: 6492

data:
  name: "RedEdge"
  root_dir: "./samples/512"
  maps: "./samples/rotated_ortho/004/RGB.png"
  map_out_name: "./results/field_004_generated_label.png"
  train_val_fields: ["001", "000", "003", "002"] # Fields to draw patches from for train/val
  test_fields: ["004"] 
  image_patch_folder: "RGB"
  gt_patch_folder: "groundtruth"
  target_size: [512, 512]
  validation_split_ratio: 0.2

train:
    n_gpus: 1
    workers: 0
    max_epoch: 100
    batch_size: 8
    overfit: False

model:
    num_classes: 4
    pre-trained: False
    lr: 0.01
    loss:
        kl_div_anneal_epochs: 25

simulator:
    path_to_orthomosaic: None
    resize_flag: false
    resize_factor: 1
    gsd: 0.003
    world_range: [4692, 3168]
    sensor:
        resolution: [1024, 1024]
        angle: [45, 45]

mapper:
  poses: [26, 9]
  map_boundary: [4692, 3168]
  ground_resolution: [0.003, 0.003]
  class_number: 4